### PR TITLE
Lint

### PR DESCRIPTION
**Pull request by GuillaumeGomez**
I guess you'll need to make another release? :-/ Sorry again.

### CODE REVIEW

**Comment by Yamakaky** [comment]
I guess not, it's a RC so it doesn't appear in `cargo outdated` and such. I just don't want to do releases with breaking changes every week, thus the RC ^^

**Comment by GuillaumeGomez** [comment]
I'll need you to make another rc though for cargo. :)

**Comment by Yamakaky** [comment]
You mean with this change?

**Comment by GuillaumeGomez** [comment]
Yes.

**Comment by Yamakaky** [comment]
Done

**Comment by GuillaumeGomez** [comment]
Thanks again!

**Pull request merged**
