### PR TITLE
Add a Sync bounds to errors

### PR DESCRIPTION
**Pull request by sfackler**
`Box<Error + Sync + Send>` is far more common than `Box<Error +
Send>` - common conveniences like conversion from strings are not
implemented for `Box<Error + Send>`, `Box<Error + Send>` cannot be
stored in `io::Error`s, etc.

This is a breaking change, but non-`Sync` errors should be rare so the
fallout shouldn't be too bad.

r? @brson I've confirmed that rustup builds without modification with this change.

### CODE REVIEW

**Comment by Yamakaky** [comment]
Do you have an example of code that requires this change?

**Comment by sfackler** [comment]
Returning an error_chain generated error as a `Box<Error + Sync + Send>`.

**Comment by Yamakaky** [comment]
Most errors are Sync I think, since they are read-only?

**Comment by sfackler** [comment]
Yep!

**Comment by Yamakaky** [comment]
Please update the changelog.

**Comment by sfackler** [comment]
Done

**Comment by Yamakaky** [comment]
> common conveniences like conversion from strings are not
implemented for Box<Error + Send>

What do you mean?

**Comment by sfackler** [comment]
This works: `let e: Box<Error> = "uh oh".into()`, as does `let e: Box<Error + Sync + Send> = "uh oh.into()`, but not `let e = Box<Error + Send> = "uh oh".into()`.

**Comment by Yamakaky** [comment]
Hum, strange, do you know why?

**Comment by sfackler** [comment]
We never bothered implementing it since `Box<Error + Send>` is exceedingly rare.

**Comment by Yamakaky** [comment]
Ok, let see if it breaks something important in another crate ;)

**Comment by diwic** [comment]
JFTR, my main D-Bus error struct won't implement Sync, because it is a wrapper around an FFI struct, and as such I cannot provide any guarantees that the "C" side of the struct is (or will remain) Sync.

**Comment by Yamakaky** [comment]
That's what I feared...

**Comment by durka** [comment]
What is the suggested workaround for errors that cannot be made Sync? Can I just not use error-chain anymore?

**Comment by Yamakaky** [comment]
I'll just remove it in 0.9.

**Comment by sfackler** [comment]
Things break without the bound just as they do with it. Can we make the error bounds configurable in the `error_chain! {}` macro?

**Comment by Yamakaky** [comment]
Yes, see https://github.com/brson/error-chain/issues/121.

**Comment by jsgf** [comment]
I ran into this because `std::io::Error` requires a nested error to be `Sync`. It makes it hard to incorporate error-chain errors into interfaces with return `std::io::Result`.

**Comment by Yamakaky** [comment]
See https://github.com/brson/error-chain/issues/134

**Comment by rnewman** [comment]
Reverting this means that `error_chain` can't easily be used with `combine`. In Mentat we've had to roll back to 0.8.1 until this is fixed: https://github.com/mozilla/mentat/pull/418

**Pull request merged**
