### PR TITLE
[WIP] Core support

### LINKED ISSUE #37: Does this library allocate?
I'm wondering if this is suitable for representing errors in a potential out-of-memory condition (i.e. malloc failure)?

### PR DESCRIPTION
**Pull request by Yamakaky**
Fixes #37.

### CODE REVIEW

**Comment by brson** [comment]
Can you say more about what this branch is doing?

**Comment by Yamakaky** [comment]
I'm trying to support `core`. I'll wait for `quick-error` to support it, though.
BTW, do you know how to write generic code to std/core? I do conditional re-exports, but it would be cleaner to have it out of the box.

**Comment by tarcieri** [comment]
> I do conditional re-exports, but it would be cleaner to have it out of the box.

I would like to know a better answer to this for #157. Not sure what it would look like though. Possibly some macro refactoring?

**Comment by tarcieri** [comment]
@Yamakaky does #157 look like it covers the same goals as this PR?

**Comment by Yamakaky** [comment]
Yes

**Pull request closed without merging**
