### PR TITLE
Caused error

### PR DESCRIPTION
**Pull request by Yamakaky**
TODO:
- [ ] name?

### CODE REVIEW

**Comment by golddranks** [comment]
I tried to compile this change against my code for a test, but I had trouble updating my code to correspond with some recent commits (I think the relevant merge is https://github.com/brson/error-chain/commit/519a2c22abd4565b7794f501a8f7ffad0d69ce31). I get errors like this: "the method `chain_err` exists but the following trait bounds were not satisfied: `diesel::result::Error : error_chain::ChainedError`". This seems odd, as I have indeed declared `::diesel::result::Error, DieselError;` in the foreign links section of the `error_chain!` macro.

**Comment by Yamakaky** [comment]
Could you show me your code?

**Comment by golddranks** [comment]
https://github.com/golddranks/ganbare Here you are. (I'm working on nightly.)

**Comment by golddranks** [comment]
Note that I used to use a custom version of error-chain for some weeks, so I don't even expect that to build straight away – but the many "following trait bounds were not satisfied: `std::env::VarError : error_chain::ChainedError`" errors confuse me.

**Comment by Yamakaky** [comment]
What changes did you make to error-chain? Maybe I can merge them?

**Comment by Yamakaky** [comment]
Also, could you tell me one example about a line which fails to compile? I don't want to setup a db to compile your crate ^^

**Comment by golddranks** [comment]
I just used my own custom version of "caused error", but shouldn't be nothing relevant. I'll try to strip away the fluff to make a smaller example, just a moment.

**Comment by golddranks** [comment]
https://github.com/golddranks/ganbare/tree/test_errors How's this? Check the lib.rs.

**Comment by Yamakaky** [comment]
Rebased

**Comment by golddranks** [comment]
Thanks, that got fixed.

However, now I get very strange inference errors that look like downright inference bugs to me:

    pub fn check_session(conn : &PgConnection, session_id : &str) -> Result<(User, Session)> {
        use schema::{users, sessions};
        use diesel::ExpressionMethods;
        use diesel::result::Error::NotFound;
    
        let (session, user) : (Session, User) = sessions::table
            .inner_join(users::table)
            .filter(sessions::sess_id.eq(sess_to_bin(session_id)?))
            .get_result(conn)
            .map_err(|e| {
                let a: () = e; // Just added this line for testing
                match e {
                    e @ NotFound => e.caused_err(|| ErrorKind::NoSuchSess),
                    e => e.caused_err(|| "Database error?!"),
            }})?;
    
        Ok((user, session))
    }

errors with:

    error[E0277]: the trait bound `(): error_chain::ChainedError` is not satisfied
       --> src/lib.rs:280:35
        |
    280 |                 e @ NotFound => e.caused_err(|| ErrorKind::NoSuchSess),
        |                                   ^^^^^^^^^^ the trait `error_chain::ChainedError` is not implemented for `()`

`()`?! what the heck! e shouldn't be (). And indeed, when I uncomment the line `let a: () = e;`, it rightly says: "expected (), found enum `diesel::result::Error`". (Btw. my toolchain is nightly-2016-11-06-x86_64-apple-darwin). I'm baffled.

**Comment by golddranks** [comment]
I pushed a new test case that demonstrates the error. https://github.com/golddranks/ganbare/commit/50624b883201cb3490c4afbed51275c871ffc97b

**Comment by golddranks** [comment]
There's actually two cases of inference behaving strangely. The first one is demonstrated by `test_function`, and the second one by `get_file`.

**Comment by Yamakaky** [comment]
For the first one, you can do
```rust
let res: Result<_> = env::var("GANBARE_RUNTIME_PEPPER").chain_err(|| "Environmental variable GANBARE_RUNTIME_PEPPER must be set!");
let run_pepper = res?;
```
For the second one, it works it I do
```rust
    let file: String = get_result().map_err(|e| {
        let e2: Error = match e.kind() {
            io::ErrorKind::NotFound => e.caused_err(|| ErrorKind::FileNotFound),
            _ => e.caused_err(|| "Database error?!"),
        };
        e2
    })?;
```
In either case, it's an inference problem...

**Comment by Yamakaky** [comment]
Same problem with
```rust
    let file: String = get_result().map_err(|e| {
        e.caused_err(|| Error::from(ErrorKind::FileNotFound))
    })?;
```

**Comment by golddranks** [comment]
Btw, made a better version of the test cases that show the inference bugs, I accidentally had borked the second one, it didn't make any sense. https://github.com/golddranks/ganbare/commit/10bb75d081a9e4432e42915c4589290dc375de33

To me, these look like bugs in inference

**Comment by Yamakaky** [comment]
Yeah, it knows that `get_file` returns an `Error`, so it should infer the return value of map_err.

**Comment by golddranks** [comment]
Do you happen to know if these are known bugs? Are they recent ones or have they existed for a long time?

**Comment by Yamakaky** [comment]
That's what I'm searching. Keep me informed!

**Comment by Yamakaky** [comment]
What I *think* is happening is that the inference engine can't find the return value of `get_result().map_err()` since `try!` returns the `Result` *with `map_err(Into::into)`*. Since you can have multiple `CE: ChainedError` that implements `Into` for our `Error`, it can't choose which to use.

**Comment by Yamakaky** [comment]
```rust
    let res = get_result().map_err(|e| {
        e.caused_err(ErrorKind::FileNotFound)
    });
    //let _: () = match res {
    //    Ok(o) => o,
    //    e => return e.into(),
    //};
    //let _: () = try!(res);
    let _: () = res?;
```
The first `let _: ()` compiles, not the last two.

**Comment by Arnavion** [comment]
The `()` inference is probably https://github.com/rust-lang/rust/issues/37181

**Comment by Yamakaky** [comment]
thanks

**Pull request closed without merging**
